name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4

            - name: Install and Build 🔧
              run: |
                  npm ci
                  npm run build

            - name: 📂 Sync files via sftp
              uses: SamKirkland/FTP-Deploy-Action@v4.3.6
              with:
                  local-dir: ./dist/
                  server: ${{ secrets.ftp_host }}
                  username: ${{ secrets.ftp_user }}
                  password: ${{ secrets.ftp_password }}
                  port: 22
                  timeout: 60000
                  dangerous-clean-slate: false
